/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedVocabulariesRouteImport } from './routes/_authenticated/vocabularies'
import { Route as ApiDebugcookieRouteImport } from './routes/api/debugcookie'
import { Route as ApiGaRouteImport } from './routes/api/ga'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVocabulariesRoute =
  AuthenticatedVocabulariesRouteImport.update({
    id: '/vocabularies',
    path: '/vocabularies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiDebugcookieRoute = ApiDebugcookieRouteImport.update({
  id: '/api/debugcookie',
  path: '/api/debugcookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGaRoute = ApiGaRouteImport.update({
  id: '/api/ga',
  path: '/api/ga',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/vocabularies': typeof AuthenticatedVocabulariesRoute
  '/api/debugcookie': typeof ApiDebugcookieRoute
  '/api/ga': typeof ApiGaRoute
}
export interface FileRoutesByTo {
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/vocabularies': typeof AuthenticatedVocabulariesRoute
  '/api/debugcookie': typeof ApiDebugcookieRoute
  '/api/ga': typeof ApiGaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/vocabularies': typeof AuthenticatedVocabulariesRoute
  '/api/debugcookie': typeof ApiDebugcookieRoute
  '/api/ga': typeof ApiGaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/login'
    | '/signup'
    | '/progress'
    | '/review'
    | '/vocabularies'
    | '/api/debugcookie'
    | '/api/ga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/debug'
    | '/login'
    | '/signup'
    | '/progress'
    | '/review'
    | '/vocabularies'
    | '/api/debugcookie'
    | '/api/ga'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/debug'
    | '/login'
    | '/signup'
    | '/_authenticated/progress'
    | '/_authenticated/review'
    | '/_authenticated/vocabularies'
    | '/api/debugcookie'
    | '/api/ga'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiDebugcookieRoute: typeof ApiDebugcookieRoute
  ApiGaRoute: typeof ApiGaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vocabularies': {
      id: '/_authenticated/vocabularies'
      path: '/vocabularies'
      fullPath: '/vocabularies'
      preLoaderRoute: typeof AuthenticatedVocabulariesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/debugcookie': {
      id: '/api/debugcookie'
      path: '/api/debugcookie'
      fullPath: '/api/debugcookie'
      preLoaderRoute: typeof ApiDebugcookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ga': {
      id: '/api/ga'
      path: '/api/ga'
      fullPath: '/api/ga'
      preLoaderRoute: typeof ApiGaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedVocabulariesRoute: typeof AuthenticatedVocabulariesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedVocabulariesRoute: AuthenticatedVocabulariesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiDebugcookieRoute: ApiDebugcookieRoute,
  ApiGaRoute: ApiGaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
